# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Otomatik Profil Güncelleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 00 00 * * *
  push:
    paths:
      - guncelle.py
      - .github/workflows/keyiflerolsun.yml

jobs:
  keyiflerolsun:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: 🚀 Repository’yi Kopyala
        uses: actions/checkout@v7.0.0

      - name : 🛠️ Python 3.14.6 Yükle
        uses : actions/setup-python@v6.3.0
        with :
          python-version: 3.14.6

      - name : 📦 Gereksinimleri Yükle
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name : ⚙️ Betiği Çalıştır
        run  : |
          uv run guncelle.py

      - name : 🔍 Değişiklik Kontrolü
        id   : degisiklik_kontrol
        run  : |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name : 📤 Depoyu Güncelle
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          zaman=$(TZ=":Europe/Istanbul" date "+%d-%m-%Y %H:%M:%S | TSİ")

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --author="keyiflerolsun <keyiflerolsun@users.noreply.github.com>" \
            -m "🕰 Otomatik Paylaşım » $zaman" -m "💾 Önceki » $GITHUB_SHA"
          git push
